services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./images:/var/www/html/images
    ports:
      - 80:80
    depends_on:
      - app

  app:
    # image: registry.gitlab.com/anhpt97/nest-graphql
    build: .
    # command: yarn start:dev
    env_file: .env
    ports:
      - 3000:${PORT}
    volumes:
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
    depends_on:
      - db
      - redis

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    # volumes:
    #   - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:${DB_PORT}

  redis:
    image: redis:alpine
    ports:
      - 6379:${REDIS_PORT}
