name: CI

on: [push, pull_request, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: |
          yarn lint --max-warnings=0
          yarn tsc --noEmit
